services:
  agent-api:
    container_name: agentic-cia
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - data:/app/data
      - chroma_sac:/app/chroma_sac
    networks:
      - agentic-cia-network
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - REDIS_HOST=redis
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - agentic-cia-network
    restart: unless-stopped
    
volumes:
  data:
  chroma_sac:
  ollama_data:

networks:
  agentic-cia-network:
    name: agentic-cia-network
